version: '3'

networks:
    laravel:

services:
    app:
        build:
            context: ./.docker
            dockerfile: nginx.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html:delegated
        depends_on:
            - php
            - redis
            - composer
            - artisan
            - database
        networks:
            - laravel

    database:
        image: mariadb:10.6
        restart: unless-stopped
        container_name: seo_pages_db
        tty: true
        environment:
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_HOST: '127.0.0.1'
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        ports:
            - 33067:3306
        volumes:
            - /var/data/seo_page/database/:/var/lib/mysql/data
            - /var/data/seo_page/dump/:/var/dump
        networks:
            - laravel

    php:
        build:
            context: ./.docker
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www/html:delegated
        networks:
            - laravel

    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - laravel

    composer:
        build:
            context: ./.docker
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - ./:/var/www/html
        depends_on:
            - php
        entrypoint: [ 'composer', 'install', '--ignore-platform-reqs']
        networks:
            - laravel

    artisan:
        build:
            context: ./.docker
            dockerfile: php.dockerfile
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - ./:/var/www/html:delegated
        depends_on:
            - database
        entrypoint: [ 'php', 'artisan', 'doctrine:migrations:migrate']
        networks:
            - laravel
